export enum TypeKeys {
  ADD_SHAPE_TO_WORKSPACE = "ADD_SHAPE_TO_WORKSPACE",
  UPDATE_SHAPE_OPTIONS = "UPDATE_SHAPE_OPTIONS",
  SET_EDIT_SHAPE_OPTIONS = "SET_EDIT_SHAPE_OPTIONS",
  RESET_EDIT_SHAPES_OPTIONS = "RESET_EDIT_SHAPES_OPTIONS",
}
